[2023-07-17 12:19:37.548][D][client_logManager.py(Init):12] LogManager Init function called !!!
[2023-07-17 12:19:40.144][I][client_model.py(connect):38] Connection refused, retrying...
